export const TRAINING_STORAGE_KEY = 'gym-app:training:v1';

export interface TrainingSet { loadKg: number; reps: number }

/**
 * Contract supplied by the reviewed plan. IDs belong to the plan source and
 * are never generated by the recording UI.
 */
export interface TrainingRoutineItem {
  id: string;
  exerciseId: string;
  sets: number;
  reps: number | string;
  rir: number | null;
  rest: number | string | null;
  loadGuidance: string;
  instructions: string;
}

export interface TrainingRoutineSession {
  id: string;
  title: string;
  items: TrainingRoutineItem[];
}

export interface TrainingRoutineDay {
  id: string;
  label: string;
  sessions: TrainingRoutineSession[];
}

export interface TrainingRoutine {
  id: string;
  name: string;
  source: string;
  days: TrainingRoutineDay[];
}

export interface TrainingLog {
  exerciseId: string;
  sets: TrainingSet[];
  rir: number | null;
  status: 'completed' | 'partial';
  comment: string;
  updatedAt: string;
}
export interface TrainingSession {
  id: string;
  performedOn: string;
  exerciseIds: string[];
  logs: TrainingLog[];
  finishedAt: string | null;
  /** Optional fields keep older free-session records valid in storage v1. */
  mode?: 'free' | 'prepared';
  routineId?: string;
  routineDayId?: string;
  routineSessionId?: string;
  plannedItems?: TrainingRoutineItem[];
}
export interface ExerciseNote {
  id: string;
  exerciseId: string;
  author: 'Mauri' | 'Noe';
  text: string;
  updatedAt: string;
  pinned: boolean;
}
export interface TrainingData {
  version: 1;
  sessions: TrainingSession[];
  exerciseNotes: ExerciseNote[];
}

const object = (v: unknown): v is Record<string, unknown> => !!v && typeof v === 'object' && !Array.isArray(v);
const text = (v: unknown, max = 200) => typeof v === 'string' && v.length > 0 && v.length <= max;
const number = (v: unknown, max: number) => typeof v === 'number' && Number.isFinite(v) && v >= 0 && v <= max;
const timestamp = (v: unknown) => typeof v === 'string' && Number.isFinite(Date.parse(v));
export const validDate = (v: string) => /^\d{4}-\d{2}-\d{2}$/.test(v) && Number.isFinite(Date.parse(`${v}T12:00:00Z`)) && new Date(`${v}T12:00:00Z`).toISOString().slice(0, 10) === v;
const unique = (ids: string[]) => new Set(ids).size === ids.length;

const validRoutineItem = (v: unknown): v is TrainingRoutineItem => object(v) && text(v.id) && text(v.exerciseId) &&
  number(v.sets, 30) && Number.isInteger(v.sets) && Number(v.sets) > 0 &&
  ((typeof v.reps === 'number' && Number.isFinite(v.reps) && v.reps > 0 && v.reps <= 1000) || text(v.reps, 40)) &&
  (v.rir === null || number(v.rir, 10)) &&
  (v.rest === null || (typeof v.rest === 'number' && Number.isFinite(v.rest) && v.rest >= 0 && v.rest <= 3600) || text(v.rest, 80)) &&
  typeof v.loadGuidance === 'string' && v.loadGuidance.length <= 500 &&
  typeof v.instructions === 'string' && v.instructions.length <= 2000;

const validLog = (v: unknown): v is TrainingLog => object(v) && text(v.exerciseId) &&
  Array.isArray(v.sets) && v.sets.length > 0 && v.sets.length <= 30 && v.sets.every(s => object(s) && number(s.loadKg, 2000) && number(s.reps, 1000) && Number.isInteger(s.reps) && Number(s.reps) > 0) &&
  (v.rir === null || number(v.rir, 10)) && (v.status === 'completed' || v.status === 'partial') &&
  typeof v.comment === 'string' && v.comment.length <= 2000 && timestamp(v.updatedAt);

const validSession = (v: unknown): v is TrainingSession => object(v) && text(v.id) && typeof v.performedOn === 'string' && validDate(v.performedOn) &&
  Array.isArray(v.exerciseIds) && v.exerciseIds.every(id => text(id)) && unique(v.exerciseIds) &&
  Array.isArray(v.logs) && v.logs.every(validLog) && unique(v.logs.map(l => l.exerciseId)) && v.logs.every(l => v.exerciseIds instanceof Array && v.exerciseIds.includes(l.exerciseId)) &&
  (v.finishedAt === null || timestamp(v.finishedAt)) &&
  (v.mode === undefined || v.mode === 'free' || v.mode === 'prepared') &&
  (v.routineId === undefined || text(v.routineId)) &&
  (v.routineDayId === undefined || text(v.routineDayId)) &&
  (v.routineSessionId === undefined || text(v.routineSessionId)) &&
  (v.plannedItems === undefined || (Array.isArray(v.plannedItems) && v.plannedItems.length <= 100 && v.plannedItems.every(validRoutineItem)));

export const validTrainingData = (v: unknown): v is TrainingData => object(v) && v.version === 1 &&
  Array.isArray(v.sessions) && v.sessions.every(validSession) && unique(v.sessions.map(s => s.id)) &&
  v.sessions.filter(s => s.finishedAt === null).length <= 1 &&
  Array.isArray(v.exerciseNotes) && v.exerciseNotes.every(n => object(n) && text(n.id) && text(n.exerciseId) &&
    (n.author === 'Mauri' || n.author === 'Noe') && text(n.text, 2000) && timestamp(n.updatedAt) && typeof n.pinned === 'boolean') &&
  unique(v.exerciseNotes.map(n => n.id));

export const readTraining = (): { data: TrainingData; raw: string | null; error: string } => {
  const empty: TrainingData = { version: 1, sessions: [], exerciseNotes: [] };
  try {
    const raw = localStorage.getItem(TRAINING_STORAGE_KEY);
    if (raw === null) return { data: empty, raw, error: '' };
    const data: unknown = JSON.parse(raw);
    if (!validTrainingData(data)) throw new Error('invalid');
    return { data, raw, error: '' };
  } catch {
    return { data: empty, raw: null, error: 'No pude leer tus registros locales. No voy a sobrescribirlos. Conservá este navegador y revisemos el problema antes de continuar.' };
  }
};

export const saveTraining = (data: TrainingData, previousRaw: string | null): string => {
  if (!validTrainingData(data)) throw new Error('El registro contiene datos no válidos. Revisá los campos.');
  try {
    // ponytail: compare-before-write protects normal multi-tab edits; a remote repository needs transactional revisions.
    if (localStorage.getItem(TRAINING_STORAGE_KEY) !== previousRaw) {
      throw new Error('changed');
    }
    const raw = JSON.stringify(data);
    localStorage.setItem(TRAINING_STORAGE_KEY, raw);
    return raw;
  } catch (error) {
    if (error instanceof Error && error.message === 'changed') throw new Error('Los registros cambiaron en otra pestaña. Copiá lo que estabas escribiendo y recargá antes de guardar.');
    throw new Error('No se pudo guardar en este navegador. Tus cambios siguen en pantalla; no cierres la página.');
  }
};

// Works on the LAN HTTP preview too, where crypto.randomUUID may be unavailable.
export const trainingId = () => Array.from(crypto.getRandomValues(new Uint32Array(4)), n => n.toString(16).padStart(8, '0')).join('');
