export interface TrainingSet {
  loadKg: number;
  reps: number;
  /** Missing fields are historical unknowns, never reconstructed measurements. */
  rir?: number | null;
  kind?: 'work' | 'warmup';
  recordedAt?: string;
}

/**
 * Contract supplied by the reviewed plan. IDs belong to the plan source and
 * are never generated by the recording UI.
 */
export interface TrainingRoutineAlternative {
  exerciseId: string;
  reps?: number | string;
  rest?: number | string | null;
  instructions?: string;
}

export interface TrainingRoutineItem {
  alternatives?: TrainingRoutineAlternative[];
  id: string;
  exerciseId: string;
  sets: number;
  reps: number | string;
  rir: number | string | null;
  rest: number | string | null;
  loadGuidance: string;
  instructions: string;
}

export type TrainingWeekday = 'monday' | 'tuesday' | 'wednesday' | 'thursday' | 'friday' | 'saturday' | 'sunday';
export type TrainingRoutineDayKind = 'strength' | 'cardio' | 'rest' | 'mixed';
export type TrainingRoutineSessionKind = 'strength' | 'cardio';

export interface TrainingCardioStep {
  id: string;
  label: string;
  moderateMinutes: number;
}

export interface TrainingCardioPlan {
  moderateMinutes: number;
  warmupMinutes: number;
  cooldownMinutes: number;
  progressionMode: 'manual-tolerance';
  progression: TrainingCardioStep[];
  intensity: string;
  notes: string;
}

export interface TrainingRoutineSession {
  id: string;
  title: string;
  items: TrainingRoutineItem[];
  kind?: TrainingRoutineSessionKind;
  cardio?: TrainingCardioPlan;
}

export interface TrainingRoutineDay {
  id: string;
  label: string;
  sessions: TrainingRoutineSession[];
  weekday?: TrainingWeekday;
  kind?: TrainingRoutineDayKind;
}

export interface TrainingRoutine {
  id: string;
  /** Required by the remote plan contract; optional to keep pre-R1.2 callers type-compatible. */
  version?: number;
  name: string;
  source: string;
  effectiveFrom?: string;
  guidance?: string[];
  days: TrainingRoutineDay[];
}

export interface TrainingLog {
  /** Older whole-exercise records are finished; incremental records opt in. */
  recording?: 'in-progress' | 'finished';
  excludeFromProgression?: boolean;
  plannedItemId?: string;
  exerciseId: string;
  loadType?: 'external' | 'bodyweight';
  sets: TrainingSet[];
  rir: number | null;
  status: 'completed' | 'partial';
  comment: string;
  updatedAt: string;
}

export interface TrainingCardioRecord {
  plannedModerateMinutes: number;
  moderateMinutes: number;
  warmupMinutes: number;
  cooldownMinutes: number;
  comment: string;
  status: 'completed' | 'partial';
  updatedAt: string;
}

export interface TrainingSession {
  id: string;
  performedOn: string;
  exerciseIds: string[];
  logs: TrainingLog[];
  finishedAt: string | null;
  /** Optional fields keep older free-session records valid in storage v1. */
  mode?: 'free' | 'prepared';
  routineId?: string;
  routineDayId?: string;
  routineSessionId?: string;
  plannedItems?: TrainingRoutineItem[];
  planVersion?: number;
  plannedCardio?: TrainingCardioPlan;
  cardio?: TrainingCardioRecord;
}
export interface ExerciseNote {
  id: string;
  exerciseId: string;
  author: 'Mauri' | 'Noe';
  text: string;
  updatedAt: string;
  pinned: boolean;
}
export interface TrainingData {
  version: 1;
  sessions: TrainingSession[];
  exerciseNotes: ExerciseNote[];
  skippedDates?: string[];
}

const object = (v: unknown): v is Record<string, unknown> => !!v && typeof v === 'object' && !Array.isArray(v);
const text = (v: unknown, max = 200) => typeof v === 'string' && v.length > 0 && v.length <= max;
const number = (v: unknown, max: number) => typeof v === 'number' && Number.isFinite(v) && v >= 0 && v <= max;
const timestamp = (v: unknown) => typeof v === 'string' && Number.isFinite(Date.parse(v));
export const validDate = (v: string) => /^\d{4}-\d{2}-\d{2}$/.test(v) && Number.isFinite(Date.parse(`${v}T12:00:00Z`)) && new Date(`${v}T12:00:00Z`).toISOString().slice(0, 10) === v;
const unique = (ids: string[]) => new Set(ids).size === ids.length;

export const validRoutineItem = (v: unknown): v is TrainingRoutineItem => object(v) && text(v.id) && text(v.exerciseId) &&
  number(v.sets, 30) && Number.isInteger(v.sets) && Number(v.sets) > 0 &&
  ((typeof v.reps === 'number' && Number.isFinite(v.reps) && v.reps > 0 && v.reps <= 1000) || text(v.reps, 40)) &&
  (v.rir === null || number(v.rir, 10) || text(v.rir, 40)) &&
  (v.rest === null || (typeof v.rest === 'number' && Number.isFinite(v.rest) && v.rest >= 0 && v.rest <= 3600) || text(v.rest, 80)) &&
  typeof v.loadGuidance === 'string' && v.loadGuidance.length <= 500 &&
  typeof v.instructions === 'string' && v.instructions.length <= 2000 &&
  (v.alternatives === undefined || (Array.isArray(v.alternatives) && v.alternatives.length <= 10 &&
    v.alternatives.every(a => object(a) && text(a.exerciseId) && a.exerciseId !== v.exerciseId &&
      (a.reps === undefined || (typeof a.reps === 'number' && a.reps > 0 && number(a.reps, 1000)) || text(a.reps, 40)) &&
      (a.rest === undefined || a.rest === null || number(a.rest, 3600) || text(a.rest, 80)) &&
      (a.instructions === undefined || (typeof a.instructions === 'string' && a.instructions.length <= 2000))) &&
    unique(v.alternatives.map(a => a.exerciseId))));

export const validCardioPlan = (v: unknown): v is TrainingCardioPlan => object(v) &&
  number(v.moderateMinutes, 1440) && Number.isInteger(v.moderateMinutes) &&
  number(v.warmupMinutes, 1440) && Number.isInteger(v.warmupMinutes) &&
  number(v.cooldownMinutes, 1440) && Number.isInteger(v.cooldownMinutes) &&
  v.progressionMode === 'manual-tolerance' && Array.isArray(v.progression) && v.progression.length > 0 &&
  v.progression.every(step => object(step) && text(step.id) && text(step.label, 160) && number(step.moderateMinutes, 1440) && Number.isInteger(step.moderateMinutes)) &&
  typeof v.intensity === 'string' && v.intensity.length <= 1000 &&
  typeof v.notes === 'string' && v.notes.length <= 3000;

const validCardioRecord = (v: unknown): v is TrainingCardioRecord => object(v) &&
  number(v.plannedModerateMinutes, 1440) && Number.isInteger(v.plannedModerateMinutes) &&
  number(v.moderateMinutes, 1440) && Number.isInteger(v.moderateMinutes) &&
  number(v.warmupMinutes, 1440) && Number.isInteger(v.warmupMinutes) &&
  number(v.cooldownMinutes, 1440) && Number.isInteger(v.cooldownMinutes) &&
  typeof v.comment === 'string' && v.comment.length <= 2000 &&
  (v.status === 'completed' || v.status === 'partial') && timestamp(v.updatedAt);

const validPlanVersion = (v: unknown): v is number => typeof v === 'number' && number(v, 1000000) && Number.isInteger(v) && v > 0;

const validLog = (v: unknown): v is TrainingLog => object(v) &&
  (v.recording === undefined || v.recording === 'in-progress' || v.recording === 'finished') &&
  (v.excludeFromProgression === undefined || typeof v.excludeFromProgression === 'boolean') &&
  (v.loadType === undefined || v.loadType === 'external' || v.loadType === 'bodyweight') && text(v.exerciseId) && (v.plannedItemId === undefined || text(v.plannedItemId)) &&
  Array.isArray(v.sets) && v.sets.length > 0 && v.sets.length <= 30 && v.sets.every(s => object(s) && number(s.loadKg, 2000) && number(s.reps, 1000) && Number.isInteger(s.reps) && Number(s.reps) > 0 &&
    (s.rir === undefined || s.rir === null || (number(s.rir, 10) && Number.isInteger(s.rir))) &&
    (s.kind === undefined || s.kind === 'work' || s.kind === 'warmup') &&
    (s.recordedAt === undefined || timestamp(s.recordedAt))) &&
  (v.rir === null || number(v.rir, 10)) && (v.status === 'completed' || v.status === 'partial') &&
  typeof v.comment === 'string' && v.comment.length <= 2000 && timestamp(v.updatedAt);

const validSession = (v: unknown): v is TrainingSession => object(v) && text(v.id) && typeof v.performedOn === 'string' && validDate(v.performedOn) &&
  Array.isArray(v.exerciseIds) && v.exerciseIds.every(id => text(id)) && unique(v.exerciseIds) &&
  Array.isArray(v.logs) && v.logs.every(validLog) && unique(v.logs.map(l => l.plannedItemId ?? l.exerciseId)) && v.logs.every(l => {
    if (!l.plannedItemId) return v.exerciseIds instanceof Array && v.exerciseIds.includes(l.exerciseId);
    const slot = Array.isArray(v.plannedItems) && v.plannedItems.find(p => object(p) && p.id === l.plannedItemId);
    return slot && (slot.exerciseId === l.exerciseId || (Array.isArray(slot.alternatives) && slot.alternatives.some((a: unknown) => object(a) && a.exerciseId === l.exerciseId)));
  }) &&
  (v.finishedAt === null || timestamp(v.finishedAt)) &&
  (v.mode === undefined || v.mode === 'free' || v.mode === 'prepared') &&
  (v.routineId === undefined || text(v.routineId)) &&
  (v.routineDayId === undefined || text(v.routineDayId)) &&
  (v.routineSessionId === undefined || text(v.routineSessionId)) &&
  (v.plannedItems === undefined || (Array.isArray(v.plannedItems) && v.plannedItems.length <= 100 && v.plannedItems.every(validRoutineItem) && unique(v.plannedItems.map(p => p.id)) &&
    v.logs.every(l => !l.plannedItemId || !(v.logs as TrainingLog[]).some(other => !other.plannedItemId && other.exerciseId === (v.plannedItems as TrainingRoutineItem[]).find(p => p.id === l.plannedItemId)?.exerciseId)))) &&
  (v.planVersion === undefined || validPlanVersion(v.planVersion)) &&
  (v.plannedCardio === undefined || validCardioPlan(v.plannedCardio)) &&
  (v.cardio === undefined || validCardioRecord(v.cardio));

export const validTrainingData = (v: unknown): v is TrainingData => object(v) && v.version === 1 &&
  Array.isArray(v.sessions) && v.sessions.every(validSession) && unique(v.sessions.map(s => s.id)) &&
  // Earlier days or plan versions may retain unfinished drafts. Opening today's
  // assigned session must not require deleting or marking those drafts complete.
  Array.isArray(v.exerciseNotes) && v.exerciseNotes.every(n => object(n) && text(n.id) && text(n.exerciseId) &&
    (n.author === 'Mauri' || n.author === 'Noe') && text(n.text, 2000) && timestamp(n.updatedAt) && typeof n.pinned === 'boolean') &&
  unique(v.exerciseNotes.map(n => n.id)) &&
  (v.skippedDates === undefined || (Array.isArray(v.skippedDates) &&
    v.skippedDates.every(d => typeof d === 'string' && validDate(d)) && unique(v.skippedDates) &&
    !v.sessions.some(s => v.skippedDates instanceof Array && v.skippedDates.includes(s.performedOn) && (s.logs.length > 0 || s.cardio !== undefined))));

export function withSkippedDates(data: TrainingData, dates: string[], today: string): TrainingData {
  if (dates.some(d => !validDate(d) || d > today)) throw new Error('Elegí días hasta hoy.');
  const next = { ...data, skippedDates: [...new Set(dates)].sort() };
  if (!validTrainingData(next)) throw new Error('No se puede marcar un día que ya tiene registros de fuerza o cardio.');
  return next;
}

export const emptyTrainingData = (): TrainingData => ({ version: 1, sessions: [], exerciseNotes: [] });

// Works on the LAN HTTP preview too, where crypto.randomUUID may be unavailable.
export const trainingId = () => Array.from(crypto.getRandomValues(new Uint32Array(4)), n => n.toString(16).padStart(8, '0')).join('');

/** loadKg is added load, never an estimate of body mass lifted. */
export const formatTrainingSet = (set: TrainingSet, loadType?: TrainingLog['loadType']): string =>
  `${set.kind === 'warmup' ? 'Calentamiento · ' : ''}${loadType === 'bodyweight' ? `Peso corporal${set.loadKg > 0 ? ` + ${set.loadKg} kg` : ''}` : `${set.loadKg} kg`} × ${set.reps}${set.rir != null ? ` · RIR ${set.rir}` : ''}`;

export const workSets = (log: Pick<TrainingLog, 'sets'>) => log.sets.filter(s => s.kind !== 'warmup');
export const isLogFinished = (log: Pick<TrainingLog, 'recording'>) => log.recording !== 'in-progress';
export const isSessionRecorded = (session: TrainingSession) => {
  const items = session.plannedItems;
  const strength = items ? items.every(i => session.logs.some(l => isLogFinished(l) && (l.plannedItemId === i.id || (!l.plannedItemId && l.exerciseId === i.exerciseId))))
    : session.exerciseIds.every(id => session.logs.some(l => l.exerciseId === id && isLogFinished(l)));
  return (session.exerciseIds.length > 0 || !!session.plannedCardio) && strength && (!session.plannedCardio || !!session.cardio);
};
